### PR TITLE
Added Serialization and Deserialization, File creation on startup, integrated with Controllers

### PR DESCRIPTION
**Pull request by AngeloFilaseta**

### CODE REVIEW

**Comment by Tale152** [comment]
@AngeloFilaseta solve conflicts

**Comment by AngeloFilaseta** [comment]
Che palle

**Comment by AngeloFilaseta** [comment]
Done :white_flower:

**Comment by Tale152** [comment]
Good job 👍

**Comment by AngeloFilaseta** [comment]
@Tale152 Thanks 💕

**Pull request merged**
